### ISSUE TITLE
"blo build" error

### ISSUE THREAD

**Issue by britefishy** [savuir/blo#1]
hi.

root@AR:/usr/local/blo-site# blo build
No handlers could be found for logger "MARKDOWN"
Traceback (most recent call last):
  File "/usr/local/bin/blo", line 9, in <module>
    load_entry_point('blo==0.3', 'console_scripts', 'blo')()
  File "/usr/local/lib/python2.7/dist-packages/blo/blog.py", line 95, in main
    blog_action.build()
  File "/usr/local/lib/python2.7/dist-packages/blo/blog.py", line 33, in build
    page_generator = PageGenerator(self.config)
  File "/usr/local/lib/python2.7/dist-packages/blo/page_generator.py", line 21, in **init**
    'markdown.extensions.codehilite'])
  File "/usr/local/lib/python2.7/dist-packages/markdown/**init**.py", line 134, in **init**
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/**init**.py", line 166, in registerExtensions
    % (ext.**class**.**module**, ext.**class**.**name**))
ValueError: Extension "**builtin**.NoneType" must be of type: "markdown.Extension".
root@AR:/usr/local/blo-site#

how to fix it?
tks

**Comment by savuir** [comment]
Looks like you should update your Markdown module, try:
`pip install "Markdown>=2.5.2"`
Sorry for late answer. Reopen, if it doesn't help.

**Comment by luckypoem** [comment]
hi.

some questions:
1. why the newest published post is on the bottom of the homepage while the earliest published post is on the top of the homepage? it should be the reverse order,right?

2.there is no pagination?
1. i cannot publish a chinese post.
   root@AR:/usr/local/blo-site# ls _blog/pages
   2016-09-27__hello-world.md  2016-09-27__test-2.md  2016-09-28__test-3.md  2016-09-28__test4.md
   root@AR:/usr/local/blo-site# blo build

Traceback (most recent call last):
  File "/usr/local/bin/blo", line 9, in <module>
    load_entry_point('blo==0.3', 'console_scripts', 'blo')()
  File "/usr/local/lib/python2.7/dist-packages/blo-0.3-py2.7.egg/blo/blog.py", line 95, in main
    blog_action.build()
  File "/usr/local/lib/python2.7/dist-packages/blo-0.3-py2.7.egg/blo/blog.py", line 34, in build
    page_generator.generate_all()
  File "/usr/local/lib/python2.7/dist-packages/blo-0.3-py2.7.egg/blo/page_generator.py", line 127, in generate_all
    html_page, html_page_path = self._generate_html_page_and_path(content)
  File "/usr/local/lib/python2.7/dist-packages/blo-0.3-py2.7.egg/blo/page_generator.py", line 78, in _generate_html_page_and_path
    page_html = self.md.convert(content)
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 359, in convert
    source = util.text_type(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
root@AR:/usr/local/blo-site#

thank u.

**Comment by luckypoem** [comment]
the post 2016-09-27__test-2.md is in chinese,it can't be published successfully.

http://blo.bright.biz.st

**Comment by savuir** [comment]
@luckypoem I've fixed the issue with non-ascii characters, you can update to blo 0.4. 
Thanks for your report and patience.

**Comment by luckypoem** [comment]
@savuir ,now i can publish a chinese post successfully: http://blo.bright.biz.st/2016-09-28/test-2.html ,but why the newest published post is on the bottom of the homepage while the earliest published post is on the top of the homepage?

 it should be the reverse order,right?

how to fix this issue?

**Comment by savuir** [comment]
@luckypoem I've fixed the ordering, thanks for the reporting. Update to blo 0.5 and build your blog again.

**Comment by luckypoem** [comment]
@savuir ,now the ordering is normal.but how to paginate?
Tks

**Comment by savuir** [comment]
@luckypoem I've add a pagination in blo 0.6, you can set `items_per_page` in your blog config file. Thank you for the feature request.

**Comment by luckypoem** [comment]
hi.

it still doesn't take effect. 
root@AR:/usr/local/blo-site# blo build
root@AR:/usr/local/blo-site# ls
2016-09-27  2016-10-11  2016-10-19  index.html  rss.xml  tags.html
2016-09-28  2016-10-13  _blog       page0.html  tag
root@AR:/usr/local/blo-site#

i set items_per_page's value to be 5 in ./blo/default.json and ./build/lib.linux-i686-2.7/blo/default.json,and u can see in /usr/local/blo-site/, page1.html wasn't generated.and u can visit
http://blo.bright.biz.st/ , there didn't exist pagination.
